version: '3'
services:
  neo4j:
    image: neo4j:latest
    container_name: codegraph_neo4j
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - type: volume
        source: codegraph-volume-data
        target: /data
    environment:
      NEO4J_AUTH: neo4j/AdminPassword
      NEO4J_dbms_memory_pagecache_size: 2G
      NEO4J_dbms.memory.heap.initial_size: 2G
      NEO4J_dbms_memory_heap_max__size: 4G
  ui:
    image: codegraph/ui
    build:
      context: src/CodeGraph.Ui
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5005
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"

volumes:
  codegraph-volume-data:
